# Generated by Django 6.0 on 2025-12-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
