# Generated by Django 6.0 on 2026-01-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
