"""
Django settings for academy project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-fi52jia^%ic#@e-7yo5fu*654y5*ka+_pvy$9f=rlltxh#3d8i"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "insecure-dev-key")
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")

# Application definition

INSTALLED_APPS = [
    'channels',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    'rest_framework',
    'rest_framework.authtoken',
    'students', 
    'django_filters',     
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "academy.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "academy.wsgi.application"
ASGI_APPLICATION = "academy.asgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "masterdrf_db.sqlite3",
#     }
# }
import os

DB_SQLITE = "sqlite"
DB_POSTGRESQL = "postgresql"

DATABASES_ALL = {
    DB_SQLITE: {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    DB_POSTGRESQL: {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "academy"),
        "USER": os.getenv("POSTGRES_USER", "academy"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "academy"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": int(os.getenv("POSTGRES_PORT", "5432")),
    },
}

DATABASES = {"default": DATABASES_ALL[os.getenv("DJANGO_DB", DB_SQLITE)]}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"




# academy/settings.py
REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/day',    # 20 requests per day for non‑logged‑in users
        'user': '1000/day',  # 1000 requests per day per logged‑in user
        'student_create': '5/min',   # custom scope name
        'student_email': '10/hour',
    },


    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # ... pagination ...


    # Page 1,2,3 style (Default)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    
    # OR LimitOffset: ?limit=5&offset=10 (Skip first 10, show next 5)
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    
    # OR Cursor: ?cursor=cD0w (Encrypted position, best for mobile)
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
}

# # Channel layer using your existing Redis
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             'hosts': [('127.0.0.1', 6379)],
#         },
#     },
# }

# # Redis as broker + result backend
# # CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
# # CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'

# # Broker: RabbitMQ via AMQP
# CELERY_BROKER_URL = 'amqp://guest:guest@127.0.0.1:5672//'  # default vhost is '/'
# # Keep Redis as result backend
# CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'

# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'

# from kombu import Queue

# CELERY_TASK_QUEUES = (
#     Queue('celery'),          # default queue
#     Queue('reports'),         # new reports queue
# )

# CELERY_TASK_ROUTES = {
#     'students.tasks.send_welcome_email_task': {'queue': 'celery'},
#     'students.tasks.generate_report_task': {'queue': 'reports'},
# }



# Celery broker & backend
CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    "amqp://guest:guest@rabbitmq:5672//",  # default for docker
)

CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    "redis://redis:6379/1",                # default for docker
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

from kombu import Queue

CELERY_TASK_QUEUES = (
    Queue("celery"),
    Queue("reports"),
)

CELERY_TASK_ROUTES = {
    "students.tasks.send_welcome_email_task": {"queue": "celery"},
    "students.tasks.generate_report_task": {"queue": "reports"},
}

# Channels / Redis channel layer
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv("CHANNEL_REDIS_HOST", "redis"), 6379)],
        },
    },
}


# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# DEFAULT_FROM_EMAIL = 'no-reply@academy.local'
#===================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'sbzalam0099@gmail.com')          # your Gmail
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'idluwlcsaxharyzi')   # NOT your normal password

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER




# from celery.schedules import crontab

# CELERY_BEAT_SCHEDULE = {
#     "example-print-task": {
#         "task": "students.tasks.example_periodic_task",
#         "schedule": crontab(minute="*/5"),  # every 5 minutes
#     },
# }

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "heartbeat-every-minute": {
        "task": "students.tasks.heartbeat_task",
        "schedule": crontab(minute="*/1"),  # every minute
    },
}


# CORS settings (development)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server
    "http://127.0.0.1:3000",
]

# For Docker production preview
CORS_ALLOW_ALL_ORIGINS = True  # TEMP: only for dev, remove in prod